//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClassWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitnessClass
    {
        public int classID { get; set; }
        public string classTitle { get; set; }
        public string classDescription { get; set; }
        //limit character show for classDescription
        public string classDescriptionTrimmed
        {
            get
            {
                if (this.classDescription.Length > 150)
                    return this.classDescription.Substring(0, 150) + "...";
                else
                    return this.classDescription;
            }
        }
        public bool active { get; set; }
        public string thumbnail { get; set; }
        public string image { get; set; }
    }
}
